// SELAH legal documents — English.
// Source: Terms & Privacy Policy provided by user (verbatim).

export const legalEn = {
  terms: {
    title: "Terms and Conditions of the SELAH – Focus and Prayer Mobile Application",
    effective: "Effective from: 1 December 2026",
    version: "Version: 1.0",
    sections: [
      {
        heading: "1. General provisions",
        items: [
          "These Terms and Conditions set out the rules for using the SELAH – Focus and Prayer mobile application, available on devices running iOS and Android.",
          "The owner and operator of the Application is MODERN COMMUNICATION SYSTEMS SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ, with its registered office in Poznań, at ul. Jeleniogórska 16, 60-179 Poznań, Poland, entered in the register of entrepreneurs of the National Court Register under KRS number 0000441265, NIP: 7773228737, REGON: 302284564, hereinafter referred to as the “Service Provider” or the “Company”.",
          "The Service Provider may be contacted by e-mail at: MCS_KONTAKT@HOTMAIL.COM.",
          "The SELAH – Focus and Prayer Application is intended to support the User in organising time for focus, prayer, silence, reflection or personal work. The Application works as a timer based on time-interval work sessions and may display statistics concerning the use of the Application.",
          "The Application is not a religious, therapeutic, psychological, medical or advisory service. The Application does not replace a pastor, priest, spiritual director, psychologist, physician, therapist or any other specialist.",
          "By using the Application, the User accepts these Terms and Conditions and the Privacy Policy of the Application.",
        ],
      },
      {
        heading: "2. Definitions",
        items: [
          "Application — the SELAH – Focus and Prayer mobile application.",
          "Service Provider — MODERN COMMUNICATION SYSTEMS SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ.",
          "User — any person using the Application.",
          "Consumer — a natural person using the Application for purposes not directly related to their business or professional activity.",
          "Service — a digital service provided through the Application.",
          "Subscription — paid, recurring access to premium features of the Application, billed through the App Store or Google Play, with technical support from RevenueCat.",
          "RevenueCat — an external technical infrastructure provider used to manage information about purchases, subscriptions and premium entitlements.",
          "Premium Features — paid features of the Application, in particular extended statistics, additional timer settings, additional sounds, session variants, personalisation or other features indicated in the Application before purchase.",
          "Statistics — data generated by the Application concerning the use of the timer, in particular the number of sessions, session duration, focus time, streaks or activity history in the Application.",
        ],
      },
      {
        heading: "3. Nature and purpose of the Application",
        items: [
          "The Application allows the User to measure time allocated to focus, prayer, silence, reflection, study, personal work or other activities requiring concentration.",
          "The Application may allow the User to select the length of sessions, breaks, sounds, notifications, work modes and to view statistics concerning timer use.",
          "The Application is an organisational and auxiliary tool. It does not guarantee any specific spiritual, psychological, health-related, educational, professional or personal results.",
          "The User independently decides how, when and for what purpose to use the Application.",
          "The name, description or contents of the Application referring to focus, prayer, silence or reflection are functional and inspirational. They do not constitute a declaration of affiliation with any religious organisation or official religious teaching.",
          "The Application is not intended for diagnosis, treatment, therapy, crisis intervention, psychological, psychiatric, medical or spiritual counselling.",
          "In the event of health problems, mental health issues, emotional crisis, suicidal thoughts, anxiety, depression or any other difficulties requiring specialist help, the User should contact an appropriate specialist or emergency services.",
        ],
      },
      {
        heading: "4. Technical requirements",
        items: [
          "In order to use the Application, the User needs: a) a mobile device running iOS or Android; b) internet access for downloading the Application, updates, subscription verification and selected online features; c) downloading the Application from the App Store or Google Play; d) the current version of the Application or another version still supported by the Service Provider.",
          "Some functions may require access to notifications, sound settings or other system permissions.",
          "Failure to grant the required permissions may limit the operation of selected features of the Application.",
          "The User bears the costs of data transmission in accordance with the tariff of their telecommunications operator.",
        ],
      },
      {
        heading: "5. No user account",
        items: [
          "The Application does not require the User to create an account or provide an e-mail address.",
          "Premium access may be identified on the basis of technical identifiers of the Application, device, App Store account, Google Play account, transaction identifiers or data processed by RevenueCat.",
          "Uninstalling the Application, changing the device, resetting the system or changing the App Store or Google Play account may affect the ability to recognise an active subscription.",
          "The User may use the restore purchases function, if such function is available in the Application.",
        ],
      },
      {
        heading: "6. Rules for using the Application",
        items: [
          "The User undertakes to use the Application in accordance with the law, good practices, these Terms and Conditions and the purpose of the Application.",
          "It is prohibited to: a) use the Application in a manner that violates applicable law or the rights of third parties; b) attempt to bypass security measures, subscription mechanisms, payment systems or usage limits; c) interfere with the operation of the Application or the Service Provider's infrastructure; d) perform reverse engineering, decompile, copy, modify or commercially exploit the Application without the Service Provider's consent; e) use the Application for unlawful, harmful or abusive purposes.",
          "The Service Provider may limit, suspend or block access to the Application if the User violates these Terms and Conditions, applicable law, the security of the Application or the rights of third parties.",
        ],
      },
      {
        heading: "7. Timer, statistics and local activity data",
        items: [
          "The Application may generate and display statistics concerning the User's sessions, including the number of completed sessions, total time, average session duration, streaks, achievements or other activity indicators.",
          "Statistics are provided for informational and motivational purposes only.",
          "The Service Provider does not guarantee that statistics will be complete, uninterrupted, error-free or available at all times.",
          "Depending on the technical configuration of the Application, some statistics may be stored locally on the User's device or processed through external technical providers.",
          "Deleting the Application, changing the device or resetting the device may result in the loss of locally stored statistics.",
        ],
      },
      {
        heading: "8. Prayer, scripture quotes and inspirational content",
        items: [
          "The Application may display Scripture quotes, short reflections, inspirational content or prompts encouraging prayer and reflection.",
          "Such content is intended for personal reflection and does not constitute official religious teaching, theological advice, spiritual direction or pastoral counselling.",
          "The User should interpret and use such content in accordance with their own conscience, beliefs and, where appropriate, with the support of competent persons or communities.",
          "The Service Provider is not responsible for the User's personal, religious, emotional or life decisions made on the basis of content displayed in the Application.",
        ],
      },
      {
        heading: "9. Payments and subscriptions",
        items: [
          "Some functions of the Application may be paid.",
          "Payments for subscriptions and in-app purchases are processed by the App Store or Google Play and technically supported by RevenueCat.",
          "The Service Provider does not process the User's full payment card details.",
          "The price, billing period, scope of premium features, renewal terms and available promotions are presented to the User before purchase in the Application or in the App Store/Google Play purchase flow.",
          "The subscription renews automatically unless cancelled by the User in accordance with the rules of the App Store or Google Play before the end of the current billing period.",
          "The User manages the subscription, cancellation and payment method directly in the Apple ID or Google Play account settings.",
          "Deleting the Application from the device does not automatically cancel the subscription.",
          "Refunds are handled in accordance with Apple, Google Play and applicable law.",
          "The Service Provider may offer trial periods, promotions or discounts. The terms of such offers are presented before purchase.",
          "After the end of a trial period, the subscription may automatically convert into a paid subscription if the User does not cancel it in accordance with the rules of the relevant store.",
        ],
      },
      {
        heading: "10. Right of withdrawal and digital services",
        items: [
          "If the User is a consumer in the European Union, the User may have the right to withdraw from a distance contract within 14 days, subject to exceptions provided by law.",
          "The right of withdrawal may not apply to digital content or digital services where performance began before the expiry of the withdrawal period with the User's express consent and after the User acknowledged the loss of the right of withdrawal.",
          "With respect to payments made through the App Store or Google Play, withdrawal, cancellation or refund procedures may require using Apple or Google mechanisms.",
          "These Terms and Conditions do not limit the User's mandatory consumer rights.",
        ],
      },
      {
        heading: "11. Complaints",
        items: [
          "The User may submit a complaint regarding the operation of the Application to: MCS_KONTAKT@HOTMAIL.COM.",
          "The complaint should include: a) a description of the problem; b) the date on which the problem occurred; c) the device model and operating system; d) information whether the problem concerns the subscription, the operation of the Application, payment, statistics or another feature; e) screenshots or other supporting materials, if available.",
          "The Service Provider will review the complaint within 14 days of receiving it, unless applicable law provides for a different period.",
          "If the complaint requires additional information, the Service Provider may ask the User to provide it.",
          "Complaints relating to payment processing, charges, refunds or subscription cancellation may require contacting Apple or Google.",
        ],
      },
      {
        heading: "12. Liability of the Service Provider",
        items: [
          "The Service Provider exercises due care to ensure that the Application operates correctly.",
          "The Service Provider does not guarantee that the Application will operate continuously, without errors or without interruptions.",
          "The Application may be temporarily unavailable due to maintenance, updates, failures, actions of external providers, network problems or force majeure.",
          "To the maximum extent permitted by law, the Service Provider is not liable for: a) decisions made by the User on the basis of the Application; b) improper use of the Application; c) violation of these Terms and Conditions by the User; d) loss of data caused by the User's actions, device failure or external services; e) the operation of the App Store, Google Play, RevenueCat or other external providers; f) failure to achieve any expected spiritual, personal, professional, educational, psychological or health-related result.",
          "The limitations of liability do not exclude liability that cannot be excluded under applicable law, in particular towards consumers.",
        ],
      },
      {
        heading: "13. Intellectual property rights",
        items: [
          "The Application, its name, logo, interface, code, design, databases, content, graphics and functional elements are protected by law.",
          "The User receives a limited, non-exclusive, non-transferable and revocable right to use the Application in accordance with these Terms and Conditions.",
          "The User may not copy, modify, distribute, decompile, reverse engineer, sell or commercially exploit the Application without the Service Provider's consent.",
          "Content displayed in the Application may be used by the User for personal, non-commercial purposes, unless otherwise stated.",
        ],
      },
      {
        heading: "14. Minors",
        items: [
          "Minors may use the Application only with the consent of a parent or legal guardian, where such consent is required by law.",
          "The parent or legal guardian is responsible for the minor's use of the Application, including payments, subscriptions and the manner in which the Application is used.",
          "If the Service Provider receives credible information that the Application is being used by a minor without the required consent, the Service Provider may limit access to the Application or take other appropriate measures.",
        ],
      },
      {
        heading: "15. Changes to the Terms and Conditions",
        items: [
          "The Service Provider may amend these Terms and Conditions for important reasons, in particular: a) changes in law; b) changes in Application features; c) changes in the payment model; d) requirements of the App Store, Google Play or external providers; e) security reasons; f) the need to clarify provisions.",
          "The User will be informed of changes to the Terms and Conditions in the Application, on a website or in another available manner.",
          "If the User does not accept the amended Terms and Conditions, the User should stop using the Application and cancel the subscription in the App Store or Google Play.",
          "Changes do not infringe consumers' acquired rights.",
        ],
      },
      {
        heading: "16. Governing law and disputes",
        items: [
          "These Terms and Conditions are governed by Polish law, subject to mandatory consumer protection provisions applicable in the User's country of residence.",
          "Disputes with consumers will be resolved by competent courts in accordance with applicable law.",
          "Disputes with Users who are not consumers will be resolved by the court competent for the registered office of the Service Provider.",
          "Consumers may use out-of-court complaint and redress mechanisms where such rights arise from applicable law.",
        ],
      },
      {
        heading: "17. Provisions for users in the United States",
        items: [
          "If the User uses the Application in the United States, the User acknowledges that the Application is provided “as is” and “as available” to the maximum extent permitted by law.",
          "To the maximum extent permitted by law, the Service Provider disclaims all implied warranties, including warranties of merchantability, fitness for a particular purpose and non-infringement.",
          "The User may not use the Application in a manner that violates federal, state or local laws.",
          "Additional privacy rules for users in the United States, including California, are set out in the Privacy Policy.",
        ],
      },
      {
        heading: "18. Contact",
        items: [
          "For all matters relating to these Terms and Conditions, the Application, complaints or subscriptions, please contact: MCS_KONTAKT@HOTMAIL.COM.",
        ],
      },
    ],
  },
  privacy: {
    title: "Privacy Policy of the SELAH – Focus and Prayer Mobile Application",
    effective: "Effective from: 1 December 2026",
    version: "Version: 1.0",
    sections: [
      {
        heading: "1. General information",
        items: [
          "This Privacy Policy explains how the SELAH – Focus and Prayer mobile application processes Users' personal data.",
          "The data controller is MODERN COMMUNICATION SYSTEMS SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ, with its registered office in Poznań, at ul. Jeleniogórska 16, 60-179 Poznań, Poland, KRS: 0000441265, NIP: 7773228737, REGON: 302284564, hereinafter referred to as the “Controller”.",
          "The Controller may be contacted at: MCS_KONTAKT@HOTMAIL.COM.",
          "The same e-mail address may be used for privacy and personal data matters: MCS_KONTAKT@HOTMAIL.COM.",
          "If the Controller appoints a Data Protection Officer, their contact details will be indicated in this Privacy Policy.",
          "This Privacy Policy applies to Users from Poland, the European Economic Area, the United Kingdom, Switzerland and the United States, subject to the local differences described below.",
        ],
      },
      {
        heading: "2. Key information",
        items: [
          "The Application does not require the User to create an account or provide an e-mail address.",
          "The Application is a timer for focus, prayer, silence, reflection, study or personal work.",
          "The Application may generate basic statistics concerning sessions, such as the number of sessions, completed sessions, focus time, average session duration, streaks or achievements.",
          "Payments are processed by the App Store or Google Play and technically supported by RevenueCat.",
          "The Controller does not process the User's full payment card details.",
          "The Application may process technical identifiers, purchase and subscription status, diagnostic data, crash data and analytics data.",
          "The User has rights under GDPR, including the right of access, rectification, erasure, restriction, objection, data portability and the right to lodge a complaint with a supervisory authority.",
        ],
      },
      {
        heading: "3. Data we may process",
        items: [
          "Technical and identification data: Application installation identifier; pseudonymous User identifier; device model, operating system, Application version, language and country; IP address and approximate location inferred from the IP address; technical logs and system events.",
          "Data concerning use of the Application: number of sessions; session duration; completed or interrupted sessions; selected timer settings; use of selected functions; information about errors, crashes and performance; premium entitlement or limit status.",
          "Statistics and progress data: number of focus sessions; total focus time; average session duration; streaks, achievements and activity history; reports generated by the Application.",
          "Purchase and subscription data: subscription status; product type; start and end date of the subscription; transaction identifier; store where the purchase was made: App Store or Google Play; technical data processed by RevenueCat.",
          "Contact data, if the User voluntarily provides it: e-mail address; name or identifier; content of a message, complaint or support request.",
          "Consent and preference data: privacy consents; notification settings; analytics or marketing consents, if used; privacy preferences.",
        ],
      },
      {
        heading: "4. Data we do not require",
        items: [
          "The Application does not require the User to provide an e-mail address.",
          "The Application does not require the User to create a personal account.",
          "The Application does not require the User to provide their real name.",
          "The Application does not require the User to provide religious affiliation, health data, biometric data, document numbers or payment card details.",
          "The User should not send sensitive data, passwords, document numbers, card details, health data or data of third parties through support channels.",
        ],
      },
      {
        heading: "5. Purposes and legal bases of processing under GDPR",
        items: [
          "Providing the SELAH service, including the timer, session settings and basic functions — performance of a contract or steps taken prior to entering into a contract.",
          "Displaying statistics, reports and achievements — performance of a contract or legitimate interest in providing and improving the service.",
          "Managing subscriptions and premium access — performance of a contract.",
          "Handling complaints, support requests and communication — performance of a contract, legal obligation or legitimate interest.",
          "Security, fraud prevention and protection of claims — legitimate interest.",
          "Analytics, diagnostics, crash reporting and performance improvement — legitimate interest or consent, depending on the configuration and legal requirements.",
          "Compliance with tax, accounting and legal obligations — legal obligation.",
          "Marketing of the Controller's own services, if used — consent or legitimate interest, depending on the communication channel and applicable law.",
        ],
      },
      {
        heading: "6. Payments, App Store, Google Play and RevenueCat",
        items: [
          "Payments in the Application are processed by Apple App Store or Google Play.",
          "RevenueCat is used to technically manage purchase, subscription and premium entitlement information.",
          "The Controller may receive from RevenueCat or app stores information such as: subscription status; transaction identifier; purchased product type; renewal, expiry or cancellation date; country or store of purchase; pseudonymous User identifier.",
          "The Controller does not receive the full payment card number.",
          "Subscription management, cancellation, refunds and payment complaints may be handled through the User's Apple ID or Google Play account.",
        ],
      },
      {
        heading: "7. Notifications",
        items: [
          "The Application may send push notifications if the User grants permission in the device settings.",
          "Notifications may relate to session completion, breaks, reminders, achievements, Application functions or technical information.",
          "The User may disable notifications at any time in the iOS or Android system settings.",
        ],
      },
      {
        heading: "8. Analytics and diagnostics",
        items: [
          "We may analyse the way the Application is used in order to improve stability, security and functionality.",
          "Analytics data may include technical information, events in the Application, errors, crashes and performance data.",
          "If applicable law requires consent for certain types of analytics, we will ask the User for such consent.",
          "The User may be able to change privacy preferences in the Application or device settings.",
        ],
      },
      {
        heading: "9. External providers",
        items: [
          "Data may be transferred to the following categories of recipients: hosting and cloud infrastructure providers; Apple and Google for app distribution, payments, diagnostics and store services; RevenueCat for subscription and entitlement management; analytics providers, if used; crash reporting and error monitoring providers, if used; customer support providers, if used; legal advisers, accountants and public authorities where required by law.",
          "Implementation note: before publication, the Controller should list the actual providers used by the Application, for example RevenueCat, Firebase, Google Analytics for Firebase, Sentry, Supabase, AWS, Google Cloud, Azure or other tools, if applicable.",
        ],
      },
      {
        heading: "10. International data transfers",
        items: [
          "Data may be processed outside the European Economic Area, in particular where we use technology providers located in the United States or other countries.",
          "In such cases we apply mechanisms required by GDPR, in particular: an adequacy decision of the European Commission, if applicable; Standard Contractual Clauses; additional organisational and technical measures where required.",
          "The User may contact the Controller to obtain more information about safeguards used for international data transfers.",
        ],
      },
      {
        heading: "11. Data retention",
        items: [
          "Technical logs and diagnostic data — for the period necessary for security, diagnostics and proper operation of the Application, usually up to 12 months.",
          "Local session statistics — for as long as they remain stored in the Application or on the User's device, unless deleted earlier.",
          "Subscription data — for the duration of the subscription and for the period necessary for settlements, complaints and claims.",
          "Support and complaint data — for the period required to handle the matter and for the limitation period for claims.",
          "Accounting and tax data — for the period required by law.",
          "Data processed on the basis of consent — until consent is withdrawn, unless another legal basis applies.",
        ],
      },
      {
        heading: "12. User rights",
        items: [
          "Right to access their data.",
          "Right to rectify their data.",
          "Right to erase their data.",
          "Right to restrict processing.",
          "Right to data portability.",
          "Right to object to processing.",
          "Right to withdraw consent at any time, where processing is based on consent.",
          "Right to lodge a complaint with a supervisory authority. In Poland, the supervisory authority is the President of the Personal Data Protection Office.",
          "Requests may be sent to: MCS_KONTAKT@HOTMAIL.COM.",
        ],
      },
      {
        heading: "13. Minors and children",
        items: [
          "Minors may use the Application only with the consent of a parent or legal guardian, where such consent is required by law.",
          "In the European Union, the processing of a child's personal data in relation to information society services requires parental consent if the child has not reached the age specified by the law of the relevant Member State.",
          "In Poland, the age for independent consent in information society services is 16.",
          "In the United States, the Children's Online Privacy Protection Act may apply if the Application is directed to children under 13 or if the Controller has actual knowledge that it collects personal data from children under 13.",
          "A parent or legal guardian may contact the Controller to request access to, deletion of or restriction of the processing of a child's data.",
          "If the Controller learns that it has processed data of a child without the required consent, it may delete the data or take other appropriate measures.",
        ],
      },
      {
        heading: "14. Automated processing",
        items: [
          "The Application may automatically process technical data, session data and subscription data in order to provide the timer, statistics, reports, achievements and premium access.",
          "The Application does not make decisions that produce legal effects concerning the User or similarly significantly affect the User within the meaning of GDPR.",
          "Statistics, achievements and reports are informational and motivational only.",
        ],
      },
      {
        heading: "15. Security",
        items: [
          "We apply technical and organisational measures intended to protect data against unauthorised access, loss, alteration or disclosure.",
          "These measures may include encrypted transmission, access control, pseudonymisation of identifiers, monitoring of errors and abuse, and limiting access to data to persons and providers who need it.",
          "No method of transmission or storage of data is completely risk-free.",
        ],
      },
      {
        heading: "16. Marketing and advertising",
        items: [
          "If the Application uses marketing, advertising or tracking technologies, the User will be informed in accordance with applicable law and platform requirements.",
          "If required by law or Apple/Google policies, the User will be asked for consent.",
          "The User may limit advertising tracking in the iOS or Android system settings.",
          "If the Application does not use behavioural advertising, the following statement applies: the Application does not display behavioural advertising and does not sell Users' personal data to advertisers.",
        ],
      },
      {
        heading: "17. Users from California and other US states",
        items: [
          "If the User is a resident of California or another US state with applicable privacy laws, the User may have additional rights, including the right to know, access, delete, correct and opt out of certain data sharing or sale practices, where applicable.",
          "The Controller does not sell personal data in the traditional meaning of the term.",
          "If the Application uses advertising technologies that may be considered a “sale” or “sharing” under applicable US privacy laws, the User will be provided with an appropriate opt-out mechanism.",
          "Privacy requests may be sent to: MCS_KONTAKT@HOTMAIL.COM.",
        ],
      },
      {
        heading: "18. App Store and Google Play",
        items: [
          "The Application is distributed through the App Store and Google Play.",
          "Apple and Google may process the User's data in accordance with their own terms and privacy policies.",
          "The Controller is not responsible for independent actions of Apple or Google as separate data controllers.",
          "The User should review the privacy settings of their Apple ID or Google account.",
        ],
      },
      {
        heading: "19. Changes to this Privacy Policy",
        items: [
          "This Privacy Policy may be amended in particular in the event of: changes in law; changes in Application features; changes in technology providers; changes in data processing practices; requirements of the App Store, Google Play or supervisory authorities.",
          "Users will be informed of material changes in the Application or by another available method.",
          "The current version of the Privacy Policy will be available in the Application or on a website.",
        ],
      },
      {
        heading: "20. Contact",
        items: [
          "For privacy, personal data, Application, complaint or subscription matters, please contact: MCS_KONTAKT@HOTMAIL.COM.",
        ],
      },
    ],
  },
};
